name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  npm_security_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start Back End
      run: npm start-be &
    - name: Sleep for 5 seconds
      run: sleep 5
    - name: Start Front End
      run: npm start-fe &
    - name: Sleep for 5 seconds
      run: sleep 5    
    - name: Run Security Tests
      run: npm run test-npm-security

  ui_tests:
    runs-on: ubuntu-latest
    needs: npm_security_tests
    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start Back End
      run: npm start-be &
    - name: Sleep for 5 seconds
      run: sleep 5
    - name: Start Front End
      run: npm start-fe &
    - name: Sleep for 5 seconds
      run: sleep 5
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Run UI tests
      run: npm run test-ui
